### ISSUE TITLE
Deal with all handle/ark/link issues

### ISSUE THREAD

**Issue by mbklein** [nulib/avalon#447]
- [ ] Display `https` URLs in all share/embed sheets
- [ ] ~Make sure new works are generating arks~
- [ ] ~Generate arks for all existing works~
- [ ] ~Redirect existing handles to arks (batch SQL update via @d-venckus)~
- [ ] Verify all works have `media.` style permalinks (straight to AVR)
- [ ] Update links in existing course reserves w/Kurt

**Comment by davidschober** [comment]
I removed it from the chores epic as that's for this release. Per MBK/DS slack pointed at around 8ish.

**Comment by davidschober** [comment]
@mbklein let's handle this during the spin down. I'd like to get this off our plate.

**Comment by mbklein** [comment]
@davidschober I did some investigating on this today because I wanted to refresh my memory. I thought it was going to be pretty easy, but unfortunately, not so much.

* We haven't been generating ARKs for new works in AVR since the Terraform cutover in June 2018. I don't remember why.
* Media Objects in Avalon have a single Permalink, not one per Section, so I don't know how we would support deep-linking using ARKs.

Generating ARKs for Media Objects and replacing the URLs in the handle server with those ARKs is reasonably straightforward. But that last part is going to be a chore, unless we either alter the `MasterFile` class to support a Permalink attribute of its own or store section-level ARKs separately. But either of those options would require AVR code changes, not just configuration changes.

**Comment by davidschober** [comment]
If it only supports one per section why would we deep link using arks. I’m confused by that last part.

Sent from my iPhone

On Mar 23, 2021, at 11:17 PM, Michael B. Klein ***@***.***> wrote:

﻿

@davidschober<https://urldefense.com/v3/__https://github.com/davidschober__;!!Dq0X2DkFhyF93HkjWTBQKhk!CL9sqGZt-G4T6w55YMexpAL0UAlyWvhvVbOZB7yLlfe-vpBNxNzWvyWIGTbQju7B6pj4n2X7Ng$> I did some investigating on this today because I wanted to refresh my memory. I thought it was going to be pretty easy, but unfortunately, not so much.

  *   We haven't been generating ARKs for new works in AVR since the Terraform cutover in June 2018. I don't remember why.
  *   Media Objects in Avalon have a single Permalink, not one per Section, so I don't know how we would support deep-linking using ARKs.

Generating ARKs for Media Objects and replacing the URLs in the handle server with those ARKs is reasonably straightforward. But that last part is going to be a chore, unless we either alter the MasterFile class to support a Permalink attribute of its own or store section-level ARKs separately. But either of those options would require AVR code changes, not just configuration changes.

**Comment by davidschober** [comment]
Actually now I’m really confused. Each section in Avalon has a different handle. Let’s talk through this.

Sent from my iPhone

On Mar 24, 2021, at 5:28 AM, David Schober ***@***.***> wrote:

﻿ If it only supports one per section why would we deep link using arks. I’m confused by that last part.

Sent from my iPhone

On Mar 23, 2021, at 11:17 PM, Michael B. Klein ***@***.***> wrote:

﻿

@davidschober<https://urldefense.com/v3/__https://github.com/davidschober__;!!Dq0X2DkFhyF93HkjWTBQKhk!CL9sqGZt-G4T6w55YMexpAL0UAlyWvhvVbOZB7yLlfe-vpBNxNzWvyWIGTbQju7B6pj4n2X7Ng$> I did some investigating on this today because I wanted to refresh my memory. I thought it was going to be pretty easy, but unfortunately, not so much.

  *   We haven't been generating ARKs for new works in AVR since the Terraform cutover in June 2018. I don't remember why.
  *   Media Objects in Avalon have a single Permalink, not one per Section, so I don't know how we would support deep-linking using ARKs.

Generating ARKs for Media Objects and replacing the URLs in the handle server with those ARKs is reasonably straightforward. But that last part is going to be a chore, unless we either alter the MasterFile class to support a Permalink attribute of its own or store section-level ARKs separately. But either of those options would require AVR code changes, not just configuration changes.

**Comment by davidschober** [comment]
Oops. I missed your edit in the wee hours. I was responding to the email notification which didn't have the edit. Disregard the above.

**Comment by davidschober** [comment]
@mbklein updated with the decision to _not_ use arks or handles in AVR

**Comment by davidschober** [comment]
@mbklein I'm still seeing hdl. links on media.northwestern.

**Comment by davidschober** [comment]
Examples from course video:

https://media.northwestern.edu/media_objects/j098zb22h

**Comment by kdid** [comment]
@mbklein - there are two places these are exposed. One is fixed, one is not.  (share link is wrong, LTI link is right). Moving back to in progress.

**Comment by kdid** [comment]
@davidschober - the script to update these is running. Please verify in a couple hours. (Brendan and I do not have access to see the link provided above)

**Comment by davidschober** [comment]
Sorry I'm still seeing hdl links in a couple of places. 

<img width="1058" alt="Screen Shot 2021-05-20 at 2 43 03 PM" src="https://user-images.githubusercontent.com/4803230/119039321-be4f9500-b979-11eb-83ac-3fac80d968aa.png">

**Comment by davidschober** [comment]
In particular "section" and "embed". Embed of course isn't critical, but I would assume it's pulling from the same places, so I'm a bit confused.

**Comment by kdid** [comment]
@mbklein and @davidschober - what is the status of this on production?

**Comment by davidschober** [comment]
I checked before leaving and it was in the same state.

**Comment by davidschober** [comment]
verified.
